export const languages = [
  { code: 'en', name: 'English' },
  { code: 'ta', name: 'Tamil (தமிழ்)' },
  { code: 'hi', name: 'Hindi (हिन्दी)' },
  { code: 'te', name: 'Telugu (తెలుగు)' },
  { code: 'kn', name: 'Kannada (ಕನ್ನಡ)' },
  { code: 'ml', name: 'Malayalam (മലയാളം)' },
  { code: 'bn', name: 'Bengali (বাংলা)' },
  { code: 'mr', name: 'Marathi (मराठी)' }
];

export const localizations = {
  en: {
    heroTitle: "Intelligent Triage & Medical Referral Assistant",
    heroSubtitle: "Describe your symptoms in your native language via text or voice. Get instant, clinical-grade triage assessments powered by advanced AI.",
    startDiagnosis: "Start Diagnosis",
    safetyDisclaimer: "Educational/Triage prototype. Not a replacement for emergency services or certified medical practitioners.",
    featuresTitle: "Key Capabilities of SwasthyaAI",
    featureVoiceTitle: "Voice-to-Text Diagnosis",
    featureVoiceDesc: "Speak naturally in your preferred language. Our system transcribes and analyzes your spoken symptoms.",
    featureMultilingualTitle: "Multilingual Support",
    featureMultilingualDesc: "Get assessments in 8 major Indian languages, custom-tailored to local medical contexts.",
    featureUrgencyTitle: "Clinical Urgency Triaging",
    featureUrgencyDesc: "Instantly categorize symptoms into Emergency, Moderate, or Low urgency levels with recommended next steps.",
    featurePdfTitle: "PDF Report Exports",
    featurePdfDesc: "Export a structured clinical summary detailing symptoms, assessment, and terminology for your doctor.",
    
    // Auth & Header
    login: "Login",
    signUp: "Sign Up",
    logout: "Logout",
    dashboard: "My Dashboard",
    backToHome: "Back to Home",
    email: "Email Address",
    password: "Password",
    fullName: "Full Name",
    alreadyHaveAccount: "Already have an account? Log in",
    dontHaveAccount: "Don't have an account? Sign up",
    submitting: "Processing...",
    
    // Symptom Intake
    symptomIntakeTitle: "Describe Your Symptoms",
    symptomInputPlaceholder: "Please describe how you are feeling, where it hurts, and when it started...",
    voiceRecordHold: "Hold to Speak",
    voiceRecordListening: "Listening... Release to stop",
    voiceRecordPermission: "Enable Microphone",
    quickSymptomChips: "Common Symptoms (Click to Add):",
    symptoms: {
      fever: "Fever",
      cough: "Dry Cough",
      breath: "Shortness of Breath",
      chest: "Chest Tightness",
      dizziness: "Dizziness",
      fatigue: "Fatigue",
      headache: "Headache",
      nausea: "Nausea"
    },
    ageGroupLabel: "Age Group",
    ageGroupSelect: "Select Age Group",
    ageGroupChild: "Child (0-12 years)",
    ageGroupTeen: "Teenager (13-19 years)",
    ageGroupAdult: "Adult (20-64 years)",
    ageGroupSenior: "Senior (65+ years)",
    durationLabel: "Symptom Duration (in days)",
    analyzeButton: "Run AI Clinical Triage",
    analyzing: "Analyzing symptoms with SwasthyaAI...",
    
    // Results
    resultsTitle: "Clinical Triage Assessment",
    emergencyWarningTitle: "CRITICAL MEDICAL EMERGENCY",
    emergencyWarningDesc: "Seek immediate in-person emergency care or call local emergency services.",
    urgencyLabel: "Urgency Classification",
    primaryAssessmentLabel: "Primary Clinical Assessment",
    contributingFactorsLabel: "Contributing Factors",
    clinicalTerminologyLabel: "Clinical Terminology",
    recommendedActionLabel: "Recommended Action",
    downloadPdfReport: "Download PDF Report",
    
    // Paywall
    paywallTitle: "Assessment Locked",
    paywallSubtitle: "Sign up or log in to view the full medical breakdown and download your clinical report.",
    
    // Dashboard
    pastAssessments: "Your Clinical History",
    noAssessments: "No past assessments found. Complete your first diagnosis to save reports here.",
    date: "Date",
    viewReport: "View",
    downloadReport: "Download PDF",
    userId: "Patient Session ID"
  },
  ta: {
    heroTitle: "புத்திசாலித்தனமான பரிசோதனை மற்றும் மருத்துவப் பரிந்துரை உதவி",
    heroSubtitle: "உங்கள் அறிகுறிகளை உங்களது தாய்மொழியில் உரை அல்லது குரல் மூலம் விவரிக்கவும். மேம்பட்ட AI மூலம் உடனடி மருத்துவப் பரிந்துரையைப் பெறுங்கள்.",
    startDiagnosis: "பரிசோதனையைத் தொடங்கு",
    safetyDisclaimer: "கல்வி/பரிசோதனை முன்மாதிரி மட்டுமே. அவசர சேவைகள் அல்லது சான்றளிக்கப்பட்ட மருத்துவ பயிற்சியாளர்களுக்கு மாற்றாகாது.",
    featuresTitle: "ஸ்வஸ்தியாAI-யின் முக்கிய திறன்கள்",
    featureVoiceTitle: "குரல் வழி உரை பரிசோதனை",
    featureVoiceDesc: "உங்கள் விருப்பமான மொழியில் பேசுங்கள். எங்களது கணினி உங்கள் குரலை உரையாக மாற்றி ஆய்வு செய்கிறது.",
    featureMultilingualTitle: "பல்மொழி ஆதரவு",
    featureMultilingualDesc: "இந்தியாவின் 8 முக்கிய மொழிகளில் உள்ளூர் மருத்துவச் சூழலுக்கு ஏற்ப மதிப்பீடுகளைப் பெறுங்கள்.",
    featureUrgencyTitle: "மருத்துவ அவசர நிலை வரிசையாக்கம்",
    featureUrgencyDesc: "பரிந்துரைக்கப்பட்ட அடுத்த கட்ட நடவடிக்கைகளுடன் அறிகுறிகளை அவசரம், நடுத்தரம் அல்லது குறைந்த நிலைகளாகப் பிரிக்கவும்.",
    featurePdfTitle: "PDF அறிக்கை ஏற்றுமதி",
    featurePdfDesc: "உங்கள் மருத்துவரிடம் காண்பிக்க அறிகுறிகள், மதிப்பீடு மற்றும் மருத்துவக் கலைச்சொற்கள் அடங்கிய அறிக்கையை ஏற்றுமதி செய்யுங்கள்.",
    login: "உள்நுழை",
    signUp: "பதிவு செய்",
    logout: "வெளியேறு",
    dashboard: "என் டாஷ்போர்டு",
    backToHome: "முகப்புக்குச் செல்",
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    fullName: "முழு பெயர்",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக",
    dontHaveAccount: "கணக்கு இல்லையா? பதிவு செய்க",
    submitting: "செயலாக்கப்படுகிறது...",
    symptomIntakeTitle: "உங்கள் அறிகுறிகளை விவரிக்கவும்",
    symptomInputPlaceholder: "நீங்கள் எப்படி உணர்கிறீர்கள், எங்கு வலிக்கிறது மற்றும் அது எப்போது தொடங்கியது என்பதை விவரிக்கவும்...",
    voiceRecordHold: "பேச அழுத்தவும்",
    voiceRecordListening: "கேட்கிறது... நிறுத்த விடுவிக்கவும்",
    voiceRecordPermission: "ஒலிவாங்கிய அனுமதி",
    quickSymptomChips: "பொதுவான அறிகுறிகள் (சேர்க்க கிளிக் செய்யவும்):",
    symptoms: {
      fever: "காய்ச்சல்",
      cough: "வறட்டு இருமல்",
      breath: "மூச்சுத் திணறல்",
      chest: "நெஞ்சு இறுக்கம்",
      dizziness: "தலைச்சுற்றல்",
      fatigue: "சோர்வு",
      headache: "தலைவலி",
      nausea: "குமட்டல்"
    },
    ageGroupLabel: "வயது பிரிவு",
    ageGroupSelect: "வயது பிரிவைத் தேர்ந்தெடுக்கவும்",
    ageGroupChild: "குழந்தை (0-12 ஆண்டுகள்)",
    ageGroupTeen: "இளைஞர் (13-19 ஆண்டுகள்)",
    ageGroupAdult: "முதிர்ந்தவர் (20-64 ஆண்டுகள்)",
    ageGroupSenior: "முதியவர் (65+ ஆண்டுகள்)",
    durationLabel: "அறிகுறி நீடித்த காலம் (நாட்களில்)",
    analyzeButton: "AI மருத்துவ பரிசோதனையை இயக்கு",
    analyzing: "ஸ்வஸ்தியாAI மூலம் அறிகுறிகளை பகுப்பாய்வு செய்கிறது...",
    resultsTitle: "மருத்துவ அவசர நிலை மதிப்பீடு",
    emergencyWarningTitle: "முக்கிய மருத்துவ அவசரநிலை",
    emergencyWarningDesc: "உடனடியாக மருத்துவமனைக்குச் செல்லுங்கள் அல்லது அவசர உதவி எண்ணை அழைக்கவும்.",
    urgencyLabel: "அவசர வகைப்பாடு",
    primaryAssessmentLabel: "முதன்மை மருத்துவ மதிப்பீடு",
    contributingFactorsLabel: "காரணிகள்",
    clinicalTerminologyLabel: "மருத்துவக் கலைச்சொற்கள்",
    recommendedActionLabel: "பரிந்துரைக்கப்பட்ட நடவடிக்கை",
    downloadPdfReport: "PDF அறிக்கை பதிவிறக்கு",
    paywallTitle: "மதிப்பீடு பூட்டப்பட்டுள்ளது",
    paywallSubtitle: "முழு மருத்துவ விவரங்களையும் பார்க்கவும் உங்கள் அறிக்கையை பதிவிறக்கவும் பதிவு செய்யவும் அல்லது உள்நுழையவும்.",
    pastAssessments: "உங்கள் மருத்துவ வரலாறு",
    noAssessments: "முந்தைய பதிவுகள் எதுவும் இல்லை. அறிக்கைகளைச் சேமிக்க உங்களது முதல் பரிசோதனையை முடிக்கவும்.",
    date: "தேதி",
    viewReport: "பார்வையிடு",
    downloadReport: "PDF பதிவிறக்கம்",
    userId: "நோயாளி அமர்வு ஐடி"
  },
  hi: {
    heroTitle: "बुद्धिमान जांच और चिकित्सा रेफरल सहायक",
    heroSubtitle: "अपनी मूल भाषा में पाठ या आवाज़ के माध्यम से अपने लक्षणों का वर्णन करें। उन्नत एआई द्वारा संचालित तत्काल, नैदानिक-स्तरीय जांच रिपोर्ट प्राप्त करें।",
    startDiagnosis: "जांच शुरू करें",
    safetyDisclaimer: "शैक्षणिक/प्रोटोटाइप मॉडल। आपातकालीन सेवाओं या प्रमाणित चिकित्सा पेशेवरों का विकल्प नहीं है।",
    featuresTitle: "SwasthyaAI की प्रमुख विशेषताएं",
    featureVoiceTitle: "आवाज़-से-पाठ निदान",
    featureVoiceDesc: "अपनी पसंद की भाषा में स्वाभाविक रूप से बोलें। हमारी प्रणाली आपके लक्षणों को रिकॉर्ड और विश्लेषण करती है।",
    featureMultilingualTitle: "बहुभाषी समर्थन",
    featureMultilingualDesc: "भारत की 8 प्रमुख भाषाओं में स्थानीय चिकित्सा संदर्भों के अनुसार अनुकूलित रिपोर्ट प्राप्त करें।",
    featureUrgencyTitle: "नैदानिक तात्कालिकता वर्गीकरण",
    featureUrgencyDesc: "लक्षणों को तुरंत आपातकालीन, मध्यम, या निम्न तात्कालिकता श्रेणियों में विभाजित कर आवश्यक कदम सुझाएं।",
    featurePdfTitle: "PDF रिपोर्ट निर्यात",
    featurePdfDesc: "अपने डॉक्टर को दिखाने के लिए लक्षणों, विश्लेषण और चिकित्सा शब्दावली युक्त एक औपचारिक रिपोर्ट डाउनलोड करें।",
    login: "लॉगिन",
    signUp: "साइन अप",
    logout: "लॉगआउट",
    dashboard: "डैशबोर्ड",
    backToHome: "होम पर जाएं",
    email: "ईमेल पता",
    password: "पासवर्ड",
    fullName: "पूरा नाम",
    alreadyHaveAccount: "पहले से खाता है? लॉगिन करें",
    dontHaveAccount: "खाता नहीं है? साइन अप करें",
    submitting: "प्रक्रिया चल रही है...",
    symptomIntakeTitle: "अपने लक्षणों का वर्णन करें",
    symptomInputPlaceholder: "कृपया बताएं कि आप कैसा महसूस कर रहे हैं, दर्द कहाँ है, और यह कब शुरू हुआ...",
    voiceRecordHold: "बोलने के लिए दबाएं",
    voiceRecordListening: "सुन रहा है... रोकने के लिए छोड़ें",
    voiceRecordPermission: "माइक्रोफ़ोन अनुमति दें",
    quickSymptomChips: "आम लक्षण (जोड़ने के लिए क्लिक करें):",
    symptoms: {
      fever: "बुखार",
      cough: "सूखी खांसी",
      breath: "सांस की तकलीफ",
      chest: "छाती में जकड़न",
      dizziness: "चक्कर आना",
      fatigue: "थकान",
      headache: "सिरदर्द",
      nausea: "उबकाई/उल्टी"
    },
    ageGroupLabel: "आयु वर्ग",
    ageGroupSelect: "आयु वर्ग चुनें",
    ageGroupChild: "बच्चा (0-12 वर्ष)",
    ageGroupTeen: "किशोर (13-19 वर्ष)",
    ageGroupAdult: "वयस्क (20-64 वर्ष)",
    ageGroupSenior: "वरिष्ठ नागरिक (65+ वर्ष)",
    durationLabel: "लक्षणों की अवधि (दिनों में)",
    analyzeButton: "AI नैदानिक जांच चलाएं",
    analyzing: "SwasthyaAI लक्षणों का विश्लेषण कर रहा है...",
    resultsTitle: "नैदानिक जांच मूल्यांकन",
    emergencyWarningTitle: "गंभीर आपातकालीन चिकित्सा स्थिति",
    emergencyWarningDesc: "तुरंत नजदीकी आपातकालीन कक्ष में जाएं या आपातकालीन सेवाओं को कॉल करें।",
    urgencyLabel: "तात्कालिकता वर्गीकरण",
    primaryAssessmentLabel: "प्राथमिक चिकित्सा मूल्यांकन",
    contributingFactorsLabel: "योगदान कारक",
    clinicalTerminologyLabel: "नैदानिक शब्दावली",
    recommendedActionLabel: "अनुशंसित कार्रवाई",
    downloadPdfReport: "PDF रिपोर्ट डाउनलोड करें",
    paywallTitle: "मूल्यांकन लॉक है",
    paywallSubtitle: "पूर्ण नैदानिक विश्लेषण देखने और अपनी रिपोर्ट डाउनलोड करने के लिए कृपया साइन अप या लॉगिन करें।",
    pastAssessments: "आपका नैदानिक इतिहास",
    noAssessments: "कोई पुराना रिकॉर्ड नहीं मिला। यहां रिपोर्ट सहेजने के लिए अपनी पहली जांच पूरी करें।",
    date: "दिनांक",
    viewReport: "देखें",
    downloadReport: "PDF डाउनलोड करें",
    userId: "मरीज सत्र आईडी"
  },
  te: {
    heroTitle: "ఇంటెలిజెంట్ ట్రయాజ్ & మెడికల్ రిఫరల్ అసిస్టెంట్",
    heroSubtitle: "మీ లక్షణాలను మీ మాతృభాషలో టెక్స్ట్ లేదా వాయిస్ ద్వారా వివరించండి. అధునాతన AI ఆధారిత తక్షణ వైద్య వర్గీకరణ నివేదికను పొందండి.",
    startDiagnosis: "పరీక్షను ప్రారంభించండి",
    safetyDisclaimer: "విద్యా/ప్రయోగాత్మక నమూనా మాత్రమే. అత్యవసర సేవలకు లేదా ధృవీకరించబడిన వైద్యులకు ప్రత్యామ్నాయం కాదు.",
    featuresTitle: "స్వస్థ్యAI యొక్క ముఖ్య సామర్థ్యాలు",
    featureVoiceTitle: "వాయిస్-టు-టెక్స్ట్ నిర్ధారణ",
    featureVoiceDesc: "మీకు నచ్చిన భాషలో సహజంగా మాట్లాడండి. మా సిస్టమ్ మీ మాటలను టెక్స్ట్‌గా మార్చి విశ్లేషిస్తుంది.",
    featureMultilingualTitle: "బహుభాషా మద్దతు",
    featureMultilingualDesc: "స్థానిక వైద్య పరిస్థితులకు తగినట్లుగా 8 ప్రధాన భారతీయ భాషలలో అంచనాలను పొందండి.",
    featureUrgencyTitle: "క్లినికల్ అర్జెన్సీ ట్రయాజ్",
    featureUrgencyDesc: "లక్షణాలను తక్షణమే అత్యవసర, మోడరేట్ లేదా తక్కువ తీవ్రత గల వర్గాలుగా విభజించి తదుపరి చర్యలను సూచిస్తుంది.",
    featurePdfTitle: "PDF నివేదిక ఎగుమతి",
    featurePdfDesc: "లక్షణాలు, అంచనా మరియు వైద్య పరిభాషలతో కూడిన అధికారిక నివేదికను మీ డాక్టర్ కోసం డౌన్‌లోడ్ చేసుకోండి.",
    login: "లాగిన్",
    signUp: "సైన్ అప్",
    logout: "లాగౌట్",
    dashboard: "నా డ్యాష్‌బోర్డ్",
    backToHome: "హోమ్ పేజీకి",
    email: "ఈమెయిల్ చిరునామా",
    password: "పాస్‌వర్డ్",
    fullName: "పూర్తి పేరు",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా? లాగిన్ అవ్వండి",
    dontHaveAccount: "ఖాతా లేదా? సైన్ అప్ అవ్వండి",
    submitting: "ప్రక్రియ కొనసాగుతోంది...",
    symptomIntakeTitle: "మీ లక్షణాలను వివరించండి",
    symptomInputPlaceholder: "మీకు ఎలా అనిపిస్తోంది, ఎక్కడ నొప్పిగా ఉంది, అది ఎప్పుడు ప్రారంభమైంది అనేవి వివరించండి...",
    voiceRecordHold: "మాట్లాడటానికి నొక్కండి",
    voiceRecordListening: "వింటోంది... ఆపడానికి వదిలేయండి",
    voiceRecordPermission: "మైక్రోఫోన్ అనుమతించు",
    quickSymptomChips: "సాధారణ లక్షణాలు (జోడించడానికి క్లిక్ చేయండి):",
    symptoms: {
      fever: "జ్వరం",
      cough: "పొడి దగ్గు",
      breath: "శ్వాస ఆడకపోవడం",
      chest: "ఛాతి బిగుతు",
      dizziness: "తల తిరగడం",
      fatigue: "అలసట",
      headache: "తలనొప్పి",
      nausea: "కడుపులో తిప్పడం/వాంతులు"
    },
    ageGroupLabel: "వయస్సు విభాగం",
    ageGroupSelect: "వయస్సు విభాగాన్ని ఎంచుకోండి",
    ageGroupChild: "పిల్లవాడు (0-12 సంవత్సరాలు)",
    ageGroupTeen: "యువకుడు (13-19 సంవత్సరాలు)",
    ageGroupAdult: "వయోజనుడు (20-64 సంవత్సరాలు)",
    ageGroupSenior: "వృద్ధుడు (65+ సంవత్సరాలు)",
    durationLabel: "లక్షణాలు ఉన్న కాలం (రోజులలో)",
    analyzeButton: "AI క్లినికల్ ట్రయాజ్ రన్ చేయి",
    analyzing: "స్వస్థ్యAI మీ లక్షణాలను విశ్లేషిస్తోంది...",
    resultsTitle: "క్లినికల్ ట్రయాజ్ నివేదిక",
    emergencyWarningTitle: "తీవ్రమైన వైద్య అత్యవసర పరిస్థితి",
    emergencyWarningDesc: "వెంటనే అత్యవసర చికిత్స కేంద్రాన్ని సందర్శించండి లేదా అత్యవసర నంబర్‌కు కాల్ చేయండి.",
    urgencyLabel: "అవసర తీవ్రత వర్గీకరణ",
    primaryAssessmentLabel: "ప్రాథమిక వైద్య అంచనా",
    contributingFactorsLabel: "ప్రభావం చూపే అంశాలు",
    clinicalTerminologyLabel: "వైద్య పరిభాష",
    recommendedActionLabel: "సిఫార్సు చేయబడిన చర్య",
    downloadPdfReport: "PDF నివేదిక డౌన్‌లోడ్ చేయి",
    paywallTitle: "రిపోర్టు లాక్ చేయబడింది",
    paywallSubtitle: "పూర్తి వైద్య విశ్లేషణను వీక్షించడానికి మరియు నివేదికను డౌన్‌లోड చేసుకోడానికి దయచేసి సైన్ అప్ లేదా లాగిన్ అవ్వండి.",
    pastAssessments: "మీ వైద్య చరిత్ర",
    noAssessments: "గత రికార్డులు ఏవీ లేవు. రిపోర్టులను సేవ్ చేయడానికి మొదటి పరీక్షను పూర్తి చేయండి.",
    date: "తేదీ",
    viewReport: "చూడండి",
    downloadReport: "PDF డౌన్‌లోడ్",
    userId: "పేషెంట్ సెషన్ ఐడి"
  },
  kn: {
    heroTitle: "ಬುದ್ಧಿವಂತ ತಪಾಸಣೆ ಮತ್ತು ವೈದ್ಯಕೀಯ ಉಲ್ಲೇಖ ಸಹಾಯಕ",
    heroSubtitle: "ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಪಠ್ಯ ಅಥವಾ ಧ್ವನಿ ಮೂಲಕ ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ. ಸುಧಾರಿತ AI ಮೂಲಕ ತ್ವರಿತ ವೈದ್ಯಕೀಯ ತಪಾಸಣೆ ವರದಿಯನ್ನು ಪಡೆಯಿರಿ.",
    startDiagnosis: "ತಪಾಸಣೆ ಪ್ರಾರಂಭಿಸಿ",
    safetyDisclaimer: "ಶೈಕ್ಷಣಿಕ/ಮಾದರಿ ತಪಾಸಣೆ ಉಪಕರಣ ಮಾತ್ರ. ತುರ್ತು ಸೇವೆಗಳು ಅಥವಾ ಪ್ರಮಾಣೀಕೃತ ವೈದ್ಯರಿಗೆ ಪರ್ಯಾಯವಲ್ಲ.",
    featuresTitle: "ಸ್ವಸ್ಥ್ಯAI ನ ಪ್ರಮುಖ ವೈಶಿಷ್ಟ್ಯಗಳು",
    featureVoiceTitle: "ಧ್ವನಿಯಿಂದ ಪಠ್ಯಕ್ಕೆ ತಪಾಸಣೆ",
    featureVoiceDesc: "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯಲ್ಲಿ ಸರಳವಾಗಿ ಮಾತನಾಡಿ. ನಮ್ಮ ವ್ಯವಸ್ಥೆಯು ಅದನ್ನು ಪಠ್ಯವಾಗಿ ಪರಿವರ್ತಿಸಿ ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.",
    featureMultilingualTitle: "ಬಹುಭಾಷಾ ಬೆಂಬಲ",
    featureMultilingualDesc: "ಸ್ಥಳೀಯ ವೈದ್ಯಕೀಯ ಸಂದರ್ಭಗಳಿಗೆ ತಕ್ಕಂತೆ ಭಾರತದ 8 ಪ್ರಮುಖ ಭಾಷೆಗಳಲ್ಲಿ ವರದಿಗಳನ್ನು ಪಡೆಯಿರಿ.",
    featureUrgencyTitle: "ವೈದ್ಯಕೀಯ ತುರ್ತು ತಪಾಸಣೆ",
    featureUrgencyDesc: "ರೋಗಲಕ್ಷಣಗಳನ್ನು ತುರ್ತು, ಮಧ್ಯಮ ಅಥವಾ ಕಡಿಮೆ ತೀವ್ರತೆಯ ಮಟ್ಟಗಳಾಗಿ ತಕ್ಷಣವೇ ವರ್ಗೀಕರಿಸಿ ಸೂಕ್ತ ಕ್ರಮಗಳನ್ನು ಸೂಚಿಸುತ್ತದೆ.",
    featurePdfTitle: "PDF ವರದಿ ರಫ್ತು",
    featurePdfDesc: "ನಿಮ್ಮ ವೈದ್ಯರಿಗೆ ತೋರಿಸಲು ರೋಗಲಕ್ಷಣಗಳು, ತಪಾಸಣೆ ಮತ್ತು ವೈದ್ಯಕೀಯ ನಿಯಮಗಳನ್ನು ಒಳಗೊಂಡ ಅಧಿಕೃತ ವರದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.",
    login: "ಲಾಗಿನ್",
    signUp: "ಸೈನ್ ಅಪ್",
    logout: "ಲಾಗಿಔಟ್",
    dashboard: "ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    backToHome: "ಮುಖಪುಟಕ್ಕೆ",
    email: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಲಾಗಿನ್ ಮಾಡಿ",
    dontHaveAccount: "ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    submitting: "ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...",
    symptomIntakeTitle: "ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ",
    symptomInputPlaceholder: "ನಿಮ್ಮ ಆರೋಗ್ಯ ಹೇಗಿದೆ, ಎಲ್ಲಿ ನೋವಾಗುತ್ತಿದೆ, ಅದು ಯಾವಾಗ ಪ್ರಾರಂಭವಾಯಿತು ಎಂಬುದನ್ನು ವಿವರಿಸಿ...",
    voiceRecordHold: "ಮಾತನಾಡಲು ಒತ್ತಿಹಿಡಿಯಿರಿ",
    voiceRecordListening: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ... ನಿಲ್ಲಿಸಲು ಬಿಡಿ",
    voiceRecordPermission: "ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ನೀಡಿ",
    quickSymptomChips: "ಸಾಮಾನ್ಯ ರೋಗಲಕ್ಷಣಗಳು (ಸೇರಿಸಲು ಕ್ಲಿಕ್ ಮಾಡಿ):",
    symptoms: {
      fever: "ಜ್ವರ",
      cough: "ಒಣ ಕೆಮ್ಮು",
      breath: "ಉಸಿರಾಟದ ತೊಂದರೆ",
      chest: "ಎದೆಯ ಬಿಗಿತ",
      dizziness: "ತಲೆಸುತ್ತು",
      fatigue: "ಆಯಾಸ",
      headache: "ತಲೆನೋವು",
      nausea: "ವಾಕರಿಕೆ/ವಾಂತಿ"
    },
    ageGroupLabel: "ವಯೋಮಾನ",
    ageGroupSelect: "ವಯೋಮಾನ ಆಯ್ಕೆಮಾಡಿ",
    ageGroupChild: "ಮಗು (0-12 ವರ್ಷಗಳು)",
    ageGroupTeen: "ಹದಿಹರೆಯದವರು (13-19 ವರ್ಷಗಳು)",
    ageGroupAdult: "ವಯಸ್ಕರು (20-64 ವರ್ಷಗಳು)",
    ageGroupSenior: "ಹಿರಿಯ ನಾಗರಿಕರು (65+ ವರ್ಷಗಳು)",
    durationLabel: "ರೋಗಲಕ್ಷಣದ ಅವಧಿ (ದಿನಗಳಲ್ಲಿ)",
    analyzeButton: "AI ವೈದ್ಯಕೀಯ ತಪಾಸಣೆ ಚಲಾಯಿಸಿ",
    analyzing: "ಸ್ವಸ್ಥ್ಯAI ನಿಮ್ಮ ರೋಗಲಕ್ಷಣಗಳನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    resultsTitle: "ವೈದ್ಯಕೀಯ ತಪಾಸಣೆ ವರದಿ",
    emergencyWarningTitle: "ತೀವ್ರ ವೈದ್ಯಕೀಯ ತುರ್ತು ಪರಿಸ್ಥಿತಿ",
    emergencyWarningDesc: "ತಕ್ಷಣವೇ ಹತ್ತಿರದ ತುರ್ತು ಚಿಕಿತ್ಸಾ ಕೇಂದ್ರಕ್ಕೆ ಹೋಗಿ ಅಥವಾ ಸಹಾಯವಾಣಿಗೆ ಕರೆ ಮಾಡಿ.",
    urgencyLabel: "ತುರ್ತು ವರ್ಗೀಕರಣ",
    primaryAssessmentLabel: "ಪ್ರಾಥಮಿಕ ವೈದ್ಯಕೀಯ ಅಂದಾಜು",
    contributingFactorsLabel: "ಕಾರಣಗಳು",
    clinicalTerminologyLabel: "ವೈದ್ಯಕೀಯ ನಿಯಮಗಳು",
    recommendedActionLabel: "ಶಿಫಾರಸು ಮಾಡಿದ ಕ್ರಮ",
    downloadPdfReport: "PDF ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    paywallTitle: "ವರದಿ ಲಾಕ್ ಆಗಿದೆ",
    paywallSubtitle: "ಸಂಪೂರ್ಣ ವೈದ್ಯಕೀಯ ವಿಶ್ಲೇಷಣೆಯನ್ನು ವೀಕ್ಷಿಸಲು ಮತ್ತು ವರದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಲು ದಯವಿಟ್ಟು ಸೈನ್ ಅಪ್ ಅಥವಾ ಲಾಗಿನ್ ಆಗಿ.",
    pastAssessments: "ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ",
    noAssessments: "ಹಿಂದಿನ ವರದಿಗಳು ಕಂಡುಬಂದಿಲ್ಲ. ಇಲ್ಲಿ ವರದಿಗಳನ್ನು ಉಳಿಸಲು ನಿಮ್ಮ ಮೊದಲ ತಪಾಸಣೆಯನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.",
    date: "ದಿನಾಂಕ",
    viewReport: "ವೀಕ್ಷಿಸಿ",
    downloadReport: "PDF ಡೌನ್‌ಲೋಡ್",
    userId: "ರೋಗಿ ಸೆಷನ್ ಐಡಿ"
  },
  ml: {
    heroTitle: "ഇന്റലിജന്റ് ട്രയാഷും മെഡിക്കൽ റഫറൽ അസിസ്റ്റന്റും",
    heroSubtitle: "നിങ്ങളുടെ രോഗലക്ഷണങ്ങൾ മാതൃഭാഷയിൽ എഴുത്തിലൂടെയോ ശബ്ദത്തിലൂടെയോ വിവരിക്കുക. നൂതന AI സാങ്കേതികവിദ്യയിലൂടെ തൽക്ഷണ മെഡിക്കൽ വർഗ്ഗീകരണ റിപ്പോർട്ട് നേടുക.",
    startDiagnosis: "പരിശോധന ആരംഭിക്കുക",
    safetyDisclaimer: "വിദ്യാഭ്യാസ/മാതൃക പരിശോധന ഉപകരണം മാത്രം. അത്യാഹിത സേവനങ്ങൾക്കോ സർട്ടിഫൈഡ് ഡോക്ടർമാർക്കോ പകരമല്ല.",
    featuresTitle: "സ്വസ്ഥ്യAI-യുടെ പ്രധാന സവിശേഷതകൾ",
    featureVoiceTitle: "വോയിസ്-ടു-ടെക്സ്റ്റ് രോഗനിർണ്ണയം",
    featureVoiceDesc: "നിങ്ങളുടെ ഇഷ്ടമുള്ള ഭാഷയിൽ സംസാരിക്കുക. ഞങ്ങളുടെ സിസ്റ്റം നിങ്ങളുടെ ശബ്ദം ടെക്സ്റ്റാക്കി മാറ്റി വിശകലനം ചെയ്യും.",
    featureMultilingualTitle: "ബഹുഭാഷാ പിന്തുണ",
    featureMultilingualDesc: "ഇന്ത്യയിലെ 8 പ്രധാന ഭാഷകളിൽ പ്രാദേശിക മെഡിക്കൽ സാഹചര്യങ്ങൾക്ക് അനുയോജ്യമായ വിലയിരുത്തലുകൾ നേടുക.",
    featureUrgencyTitle: "ക്ലിനിക്കൽ അർജൻസി ട്രയാഷ്",
    featureUrgencyDesc: "രോഗലക്ഷണങ്ങളെ എമർജൻസി, മോഡറേറ്റ് അല്ലെങ്കിൽ ലോ എന്നിങ്ങനെ തരംതിരിച്ച് അടുത്ത നടപടികൾ നിർദ്ദേശിക്കുന്നു.",
    featurePdfTitle: "PDF റിപ്പോർട്ട് എക്സ്പോർട്ട്",
    featurePdfDesc: "ഡോക്ടറെ കാണിക്കാൻ രോഗലക്ഷണങ്ങളും വിശകലനങ്ങളും ഉൾക്കൊള്ളുന്ന ഔദ്യോഗിക റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക.",
    login: "ലോഗിൻ",
    signUp: "സൈൻ അപ്പ്",
    logout: "ലോഗ് ഔട്ട്",
    dashboard: "എന്റെ ഡാഷ്‌ബോർഡ്",
    backToHome: "ഹോമിലേക്ക്",
    email: "ഇമെയിൽ വിലാസം",
    password: "പാസ്‌വേഡ്",
    fullName: "പൂർണ്ണമായ പേര്",
    alreadyHaveAccount: "മുമ്പ് അക്കൗണ്ട് എടുത്തിട്ടുണ്ടോ? ലോഗിൻ ചെയ്യുക",
    dontHaveAccount: "അക്കൗണ്ട് ഇല്ലേ? സൈൻ അപ്പ് ചെയ്യുക",
    submitting: "പ്രക്രിയ പുരോഗമിക്കുന്നു...",
    symptomIntakeTitle: "രോഗലക്ഷണങ്ങൾ വിവരിക്കുക",
    symptomInputPlaceholder: "നിങ്ങൾക്ക് എങ്ങനെയുണ്ട്, എവിടെയാണ് വേദന, എപ്പോഴാണ് തുടങ്ങിയത് എന്ന് വിവരിക്കുക...",
    voiceRecordHold: "സംസാരിക്കാൻ അമർത്തിപ്പിടിക്കുക",
    voiceRecordListening: "കേൾക്കുന്നു... നിർത്താൻ വിടുക",
    voiceRecordPermission: "മൈക്രോഫോൺ അനുവദിക്കുക",
    quickSymptomChips: "സാധാരണ രോഗലക്ഷണങ്ങൾ (ചേർക്കാൻ ക്ലിക്ക് ചെയ്യുക):",
    symptoms: {
      fever: "പനി",
      cough: "വരണ്ട ചുമ",
      breath: "ശ്വാസതടസ്സം",
      chest: "നെഞ്ചിലെ അസ്വസ്ഥത",
      dizziness: "തലകറക്കം",
      fatigue: "ക്ഷീണം",
      headache: "തലവേദന",
      nausea: "ഛർദ്ദി/മനംപിരട്ടൽ"
    },
    ageGroupLabel: "പ്രായപരിധി",
    ageGroupSelect: "പ്രായപരിധി തിരഞ്ഞെടുക്കുക",
    ageGroupChild: "കുട്ടി (0-12 വയസ്സ്)",
    ageGroupTeen: "കൗമാരക്കാരൻ (13-19 വയസ്സ്)",
    ageGroupAdult: "മുതിർന്ന ആൾ (20-64 വയസ്സ്)",
    ageGroupSenior: "വൃദ്ധൻ (65+ വയസ്സ്)",
    durationLabel: "രോഗലക്ഷണത്തിന്റെ ദൈർഘ്യം (ദിവസങ്ങളിൽ)",
    analyzeButton: "AI ക്ലിനിക്കൽ ട്രയാഷ് റൺ ചെയ്യുക",
    analyzing: "സ്വസ്ഥ്യAI നിങ്ങളുടെ രോഗലക്ഷണങ്ങൾ വിശകലനം ചെയ്യുന്നു...",
    resultsTitle: "ക്ലിനിക്കൽ ട്രയാഷ് റിപ്പോർട്ട്",
    emergencyWarningTitle: "ഗുരുതരമായ മെഡിക്കൽ അത്യാഹിതം",
    emergencyWarningDesc: "ഉടൻ തന്നെ അടുത്തുള്ള എമർജൻസി റൂമിൽ എത്തിക്കുക അല്ലെങ്കിൽ അത്യാഹിത വിഭാഗത്തിൽ ബന്ധപ്പെടുക.",
    urgencyLabel: "അടിയന്തിര സ്വഭാവ വർഗ്ഗീകരണം",
    primaryAssessmentLabel: "പ്രാഥമിക മെഡിക്കൽ വിലയിരുത്തൽ",
    contributingFactorsLabel: "പ്രധാന കാരണങ്ങൾ",
    clinicalTerminologyLabel: "മെഡിക്കൽ പദങ്ങൾ",
    recommendedActionLabel: "ശുപാർശ ചെയ്യുന്ന നടപടി",
    downloadPdfReport: "PDF റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക",
    paywallTitle: "റിപ്പോർട്ട് ലോക്ക് ചെയ്തിരിക്കുന്നു",
    paywallSubtitle: "പൂർണ്ണമായ മെഡിക്കൽ വിശകലനം കാണാനും നിങ്ങളുടെ റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യാനും ദയവായി സൈൻ അപ്പ് ചെയ്യുകയോ ലോഗിൻ ചെയ്യുകയോ ചെയ്യുക.",
    pastAssessments: "നിങ്ങളുടെ മെഡിക്കൽ ചരിത്രം",
    noAssessments: "മുൻകാല റിപ്പോർട്ടുകൾ ഒന്നും കണ്ടെത്തിയില്ല. നിങ്ങളുടെ ആദ്യ പരിശോധന പൂർത്തിയാക്കി റിപ്പോർട്ടുകൾ ഇവിടെ സംരക്ഷിക്കുക.",
    date: "തീയതി",
    viewReport: "കാണുക",
    downloadReport: "PDF ഡൗൺലോഡ്",
    userId: "പേഷ്യന്റ് സെഷൻ ഐഡി"
  },
  bn: {
    heroTitle: "বুদ্ধিমান ট্রায়াজ এবং মেডিকেল রেফারেল সহকারী",
    heroSubtitle: "আপনার নিজের ভাষায় টেক্সট বা ভয়েসের মাধ্যমে আপনার লক্ষণগুলি বর্ণনা করুন। উন্নত AI দ্বারা চালিত তাত্ক্ষণিক, ক্লিনিকাল-গ্রেড মূল্যায়ন পান।",
    startDiagnosis: "পরীক্ষা শুরু করুন",
    safetyDisclaimer: "শিক্ষামূলক/প্রোটোটাইপ মডেল। জরুরি পরিষেবা বা প্রত্যয়িত চিকিৎসকের বিকল্প নয়।",
    featuresTitle: "SwasthyaAI-এর মূল বৈশিষ্ট্যসমূহ",
    featureVoiceTitle: "ভয়েস-টু-টেক্সট নির্ণয়",
    featureVoiceDesc: "আপনার পছন্দের ভাষায় স্বাভাবিকভাবে কথা বলুন। আমাদের সিস্টেম আপনার কণ্ঠস্বর রেকর্ড এবং বিশ্লেষণ করে।",
    featureMultilingualTitle: "বহুভাষী সমর্থন",
    featureMultilingualDesc: "ভারতের ৮টি প্রধান ভাষায় স্থানীয় চিকিৎসা প্রসঙ্গের সাথে সামঞ্জস্যপূর্ণ বিশ্লেষণ পান।",
    featureUrgencyTitle: "ক্লিনিকাল জরুরি অবস্থা নির্ধারণ",
    featureUrgencyDesc: "লক্ষণগুলিকে তাত্ক্ষণিকভাবে জরুরি, মাঝারি বা কম জরুরি বিভাগে ভাগ করে প্রয়োজনীয় পদক্ষেপের পরামর্শ দিন।",
    featurePdfTitle: "PDF রিপোর্ট ডাউনলোড",
    featurePdfDesc: "আপনার ডাক্তারকে দেখানোর জন্য লক্ষণ, মূল্যায়ন এবং চিকিৎসা পরিভাষা সম্বলিত একটি আনুষ্ঠানিক প্রতিবেদন ডাউনলোড করুন।",
    login: "লগইন",
    signUp: "সাইন আপ",
    logout: "লগআউট",
    dashboard: "আমার ড্যাশবোর্ড",
    backToHome: "হোম পেজে যান",
    email: "ইমেল ঠিকানা",
    password: "পাসওয়ার্ড",
    fullName: "পূর্ণ নাম",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন",
    dontHaveAccount: "অ্যাকাউন্ট নেই? সাইন আপ করুন",
    submitting: "প্রক্রিয়া চলছে...",
    symptomIntakeTitle: "আপনার লক্ষণগুলি বর্ণনা করুন",
    symptomInputPlaceholder: "আপনি কেমন অনুভব করছেন, কোথায় ব্যথা হচ্ছে এবং এটি কখন শুরু হয়েছিল তা বর্ণনা করুন...",
    voiceRecordHold: "কথা বলার জন্য চেপে ধরুন",
    voiceRecordListening: "শুনছে... বন্ধ করতে ছেড়ে দিন",
    voiceRecordPermission: "মাইক্রোফোন অনুমতি দিন",
    quickSymptomChips: "সাধারণ লক্ষণ (যোগ করতে ক্লিক করুন):",
    symptoms: {
      fever: "জ্বর",
      cough: "শুকনো কাশি",
      breath: "শ্বাসকষ্ট",
      chest: "বুকে জকড়ন",
      dizziness: "মাথা ঘোরা",
      fatigue: "ক্লান্তি",
      headache: "মাথাব্যথা",
      nausea: "বমি বমি ভাব"
    },
    ageGroupLabel: "বয়স গ্রুপ",
    ageGroupSelect: "বয়স গ্রুপ নির্বাচন করুন",
    ageGroupChild: "শিশু (০-১২ বছর)",
    ageGroupTeen: "কিশোর (১৩-১৯ বছর)",
    ageGroupAdult: "প্রাপ্তবয়স্ক (২০-৬৪ বছর)",
    ageGroupSenior: "বয়স্ক ব্যক্তি (৬৫+ বছর)",
    durationLabel: "লক্ষণগুলির সময়কাল (দিনে)",
    analyzeButton: "AI ক্লিনিকাল ট্রায়াজ চালান",
    analyzing: "SwasthyaAI লক্ষণগুলি বিশ্লেষণ করছে...",
    resultsTitle: "ক্লিনিকাল ট্রায়াজ মূল্যায়ন",
    emergencyWarningTitle: "গুরুতর জরুরি চিকিৎসা পরিস্থিতি",
    emergencyWarningDesc: "অবিলম্বে নিকটস্থ জরুরি বিভাগে যান বা জরুরি নম্বরে কল করুন।",
    urgencyLabel: "জরুরি অবস্থা শ্রেণীবিভাগ",
    primaryAssessmentLabel: "প্রাথমিক চিকিৎসা মূল্যায়ন",
    contributingFactorsLabel: "অবদানকারী উপাদান",
    clinicalTerminologyLabel: "চিকিৎসা পরিভাষা",
    recommendedActionLabel: "প্রস্তাবিত পদক্ষেপ",
    downloadPdfReport: "PDF রিপোর্ট ডাউনলোড করুন",
    paywallTitle: "মূল্যায়ন লক করা আছে",
    paywallSubtitle: "সম্পূর্ণ ক্লিনিকাল বিশ্লেষণ দেখতে এবং রিপোর্ট ডাউনলোড করতে অনুগ্রহ করে সাইন আপ বা লগইন করুন।",
    pastAssessments: "আপনার ক্লিনিকাল ইতিহাস",
    noAssessments: "কোনো পুরনো রেকর্ড পাওয়া যায়নি। এখানে রিপোর্ট সংরক্ষণ করতে আপনার প্রথম পরীক্ষাটি সম্পন্ন করুন।",
    date: "তারিখ",
    viewReport: "দেখুন",
    downloadReport: "PDF ডাউনলোড",
    userId: "রোগী সেশন আইডি"
  },
  mr: {
    heroTitle: "बुद्धीमान ट्रायज आणि वैद्यकीय संदर्भ सहाय्यक",
    heroSubtitle: "तुमच्या मातृभाषेत मजकूर किंवा आवाजाद्वारे तुमच्या लक्षणांचे वर्णन करा. प्रगत AI द्वारे समर्थित त्वरित, वैद्यकीय-स्तरीय तपासणी अहवाल मिळवा.",
    startDiagnosis: "तपासणी सुरू करा",
    safetyDisclaimer: "शैक्षणिक/प्रोटोटाइप मॉडेल. आणीबाणीच्या सेवा किंवा प्रमाणित डॉक्टरांना पर्याय नाही.",
    featuresTitle: "SwasthyaAI ची प्रमुख वैशिष्ट्ये",
    featureVoiceTitle: "आवाज-ते-मजकूर निदान",
    featureVoiceDesc: "तुमच्या आवडीच्या भाषेत नैसर्गिकरित्या बोला. आमची प्रणाली तुमच्या बोललेल्या लक्षणांचे रेकॉर्डिंग आणि विश्लेषण करते.",
    featureMultilingualTitle: "बहुभाषिक समर्थन",
    featureMultilingualDesc: "भारतातील ८ प्रमुख भाषांमध्ये स्थानिक वैद्यकीय संदर्भांनुसार सानुकूलित अहवाल मिळवा.",
    featureUrgencyTitle: "वैद्यकीय निकड वर्गीकरण",
    featureUrgencyDesc: "पुढील शिफारस केलेल्या उपायांसह लक्षणांचे तात्काळ आणीबाणी, मध्यम किंवा कमी निकडीच्या श्रेणींमध्ये वर्गीकरण करा.",
    featurePdfTitle: "PDF अहवाल डाउनलोड",
    featurePdfDesc: "तुमच्या डॉक्टरांना दाखवण्यासाठी लक्षणे, विश्लेषण आणि वैद्यकीय शब्दावलीचा एक औपचारिक अहवाल डाउनलोड करा.",
    login: "लॉगिन",
    signUp: "साइन अप",
    logout: "लॉगआउट",
    dashboard: "माझा डॅशबोर्ड",
    backToHome: "मुख्य पानावर जा",
    email: "ईमेल पत्ता",
    password: "पासवर्ड",
    fullName: "पूर्ण नाव",
    alreadyHaveAccount: "आधीच खाते आहे? लॉगिन करा",
    dontHaveAccount: "खाते नाही? साइन अप करा",
    submitting: "प्रक्रिया सुरू आहे...",
    symptomIntakeTitle: "तुमच्या लक्षणांचे वर्णन करा",
    symptomInputPlaceholder: "तुम्हाला कसे वाटत आहे, कुठे दुखत आहे, आणि ते कधी सुरू झाले याचे वर्णन करा...",
    voiceRecordHold: "बोलण्यासाठी दाबा",
    voiceRecordListening: "ऐकत आहे... थांबवण्यासाठी सोडा",
    voiceRecordPermission: "मायक्रोफोन परवानगी द्या",
    quickSymptomChips: "सामान्य लक्षणे (जोडण्यासाठी क्लिक करा):",
    symptoms: {
      fever: "ताप",
      cough: "कोरडा खोकला",
      breath: "श्वास घेण्यास त्रास",
      chest: "छातीतील जकडन",
      dizziness: "चक्कर येणे",
      fatigue: "थकवा",
      headache: "डोकेदुखी",
      nausea: "मळमळ/उलटी"
    },
    ageGroupLabel: "वयोगट",
    ageGroupSelect: "वयोगट निवडा",
    ageGroupChild: "मुलगा (०-१२ वर्षे)",
    ageGroupTeen: "तरुण (१३-१९ वर्षे)",
    ageGroupAdult: "प्रौढ (२०-६४ वर्षे)",
    ageGroupSenior: "ज्येष्ठ नागरिक (६५+ वर्षे)",
    durationLabel: "लक्षणांचा कालावधी (दिवसांमध्ये)",
    analyzeButton: "AI वैद्यकीय ट्रायज चालवा",
    analyzing: "SwasthyaAI लक्षणांचे विश्लेषण करत आहे...",
    resultsTitle: "वैद्यकीय ट्रायज अहवाल",
    emergencyWarningTitle: "गंभीर वैद्यकीय आणीबाणी",
    emergencyWarningDesc: "त्वरित जवळच्या आणीबाणी कक्षात जा किंवा वैद्यकीय मदतीसाठी कॉल करा.",
    urgencyLabel: "निकडीचे वर्गीकरण",
    primaryAssessmentLabel: "प्राथमिक वैद्यकीय मूल्यमापन",
    contributingFactorsLabel: "योगदान देणारे घटक",
    clinicalTerminologyLabel: "वैद्यकीय संज्ञा",
    recommendedActionLabel: "शिफारस केलेली कृती",
    downloadPdfReport: "PDF अहवाल डाउनलोड करा",
    paywallTitle: "अहवाल लॉक केला आहे",
    paywallSubtitle: "पूर्ण वैद्यकीय विश्लेषण पाहण्यासाठी आणि अहवाल डाउनलोड करण्यासाठी कृपया साइन अप किंवा लॉगिन करा.",
    pastAssessments: "तुमचा वैद्यकीय इतिहास",
    noAssessments: "मागील रेकॉर्ड आढळले नाहीत. अहवाल जतन करण्यासाठी तुमची पहिली तपासणी पूर्ण करा.",
    date: "दिनांक",
    viewReport: "पहा",
    downloadReport: "PDF डाउनलोड",
    userId: "रुग्ण सत्र आयडी"
  }
};
